---
- id: Dublin
  latitude: 53.2771
  longitude: -6.4149
  country: Ireland
- id: Mumbai
  latitude: 19.0760
  longitude: 72.8777
  country: India
- id: Atlanta
  latitude: 33.7490
  longitude: -84.3880
  country: USA
- id: Sacramento
  latitude: 38.5816
  longitude: -121.4944
  country: USA
- id: Sydney
  latitude: -33.8688
  longitude: 151.2093
  country: Australia  
