---
# TODO Add employees id for each DC
- id: Ireland
  latitude: 53.2771
  longitude: -6.4149
  city: Dublin
  country: Ireland
  country_code: IE
  country_code3: IRL
- id: Mumbai
  latitude: 19.0760
  longitude: 72.8777
  city: Mumbai
  country: India
  country_code: IN
  country_code3: IND
- id: Atlanta, US
  latitude: 33.7490
  longitude: -84.3880
  city: Atlanta
  country: USA
  country_code: US
  country_code3: USA
- id: Sacramento, US
  latitude: 38.5816
  longitude: -121.4944
  city: Sacramento
  country: USA
  country_code: US
  country_code3: USA
- id: Sydney
  latitude: -33.8688
  longitude: 151.2093
  city: Sydney
  country: Australia
  country_code: AU
  country_code3: AUS